name: Rollout new version

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Select the tag to rollout'
        required: true
        type: string

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ref is a tag
        id: check-tag
        run: |
          if [[ ! "${{ github.event.inputs.ref }}" =~ ^refs/tags/ ]]; then
            echo "Selected ref is not a tag: ${{ github.event.inputs.ref }}"
            exit 1
          fi

  rollout:
    needs: check-tag
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Get latest release-prod workflow run
        id: get-workflow-run
        run: |
          # Get the version from tag (removing refs/tags/)
          VERSION=$(echo "${{ github.event.inputs.ref }}" | sed 's/refs\/tags\///')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Get the latest successful run number for the version tag
          RUN_NUMBER=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/workflows/release-prod.yml/runs \
            --jq ".workflow_runs[] | select(.head_branch == \"refs/tags/$VERSION\" and .conclusion == \"success\") | .run_number" \
            | head -n1)
          
          if [ -z "$RUN_NUMBER" ]; then
            echo "No successful workflow run found for tag $VERSION"
            exit 1
          fi
          
          echo "run_number=$RUN_NUMBER" >> $GITHUB_OUTPUT
          echo "full_version=${VERSION}.${RUN_NUMBER}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Install AWS CLI v2 (R2 compatible version)
        id: install_aws_cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.25.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/          

      - name: Update updates.json on R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          export AWS_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
          export AWS_ENDPOINT_URL=https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
          aws s3 rm s3://shinkai-download/shinkai-desktop/binaries/production/updates.json --endpoint-url https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
          aws s3 mv s3://shinkai-download/shinkai-desktop/binaries/production/updates-next.json s3://shinkai-download/shinkai-desktop/binaries/production/updates.json --endpoint-url https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com

      - name: Update Cloudflare Ruleset
        run: |
          # Load rules from secret and replace version
          RULES=$(echo '${{ secrets.CLOUDFLARE_RULES }}' | sed "s/SHINKAI_RELEASE_VERSION/${{ steps.get-workflow-run.outputs.full_version }}/g")
          
          curl -L -X PUT "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/rulesets/${{ secrets.CLOUDFLARE_RULESET_ID }}" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_AUTH_KEY }}" \
            --data "{
              \"description\": \"\",
              \"id\": \"${{ secrets.CLOUDFLARE_RULESET_ID }}\",
              \"kind\": \"zone\",
              \"name\": \"default\",
              \"phase\": \"http_request_dynamic_redirect\",
              \"rules\": ${RULES}
            }" 